FROM kolla/debian-source-nova-api:victoria
MAINTAINER Arnaud Morin "arnaud.morin@gmail.com"
COPY data/config.json /var/lib/kolla/config_files/config.json
COPY data/nova-metadata-wsgi.conf /etc/apache2/conf-enabled/nova-metadata-wsgi.conf
