FROM kolla/cinder-base:2024.2-debian-bookworm
MAINTAINER Arnaud Morin "arnaud.morin@gmail.com"
COPY data/sources.list /etc/apt/sources.list
COPY data/cinder-wsgi.conf /etc/apache2/conf-enabled/cinder-wsgi.conf
USER root
