FROM kolla/placement-base:2024.2-debian-bookworm
MAINTAINER Arnaud Morin "arnaud.morin@gmail.com"
COPY data/sources.list /etc/apt/sources.list
COPY data/placement-wsgi.conf /etc/apache2/conf-enabled/placement-wsgi.conf
