FROM kolla/debian-source-placement-api:wallaby
MAINTAINER Arnaud Morin "arnaud.morin@gmail.com"
COPY data/config.json /var/lib/kolla/config_files/config.json
COPY data/placement-wsgi.conf /etc/apache2/conf-enabled/placement-wsgi.conf
