FROM kolla/debian-source-mistral-api:wallaby
MAINTAINER Arnaud Morin "arnaud.morin@gmail.com"
COPY data/config.json /var/lib/kolla/config_files/config.json
COPY data/mistral-wsgi.conf /etc/apache2/conf-enabled/mistral-wsgi.conf
