FROM kolla/debian-source-cinder-api:wallaby
MAINTAINER Arnaud Morin "arnaud.morin@gmail.com"
COPY data/config.json /var/lib/kolla/config_files/config.json
COPY data/cinder-wsgi.conf /etc/apache2/conf-enabled/cinder-wsgi.conf
